app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.list_orders, name='list_orders'),
    path('create/', views.create_order, name='create_order'),
    path('<int:order_id>/pdf/', views.order_pdf, name='order_pdf'),
    path('delete/<int:o_id>/', views.delete_order, name='delete_order'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('where/', views.where, name='where'),
    path('<int:page>/', views.index, name='products_by_page'),
    path('products/<int:page>/<slug:category_slug>/', views.index, name='products_by_category'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.contrib.auth.models import User
from django.db import models

from shop.models import Product


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')

    def total_price(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.cart.user.username + ' - ' + self.product.name

    class Meta:
        verbose_name = 'Продукт в корзине'
        verbose_name_plural = 'Продукты в корзине'

cart/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import BadRequest
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_POST

from cart.models import Cart, CartItem
from shop.models import Product


@login_required
def cart_detail(request):
    cart = get_object_or_404(Cart, user=request.user)
    cart_items = cart.items.all()
    total_price = sum(item.total_price() for item in cart_items)
    return render(
        request,
        'cart/cart_detail.html',
        {'cart_items': cart_items, 'total_price': total_price}
    )


@login_required
@require_POST
def cart_add(request, product_id):
    cart = get_object_or_404(Cart, user=request.user)
    product = get_object_or_404(Product, id=product_id, amount__gt=0)
    try:
        cart_item = cart.items.get(product=product)
    except CartItem.DoesNotExist:
        CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
    else:
        if product.amount - (cart_item.quantity + 1) >= 0:
            cart_item.quantity += 1
            cart_item.save()
        else:
            raise BadRequest('Не хватает единиц на складе')

    return redirect('cart:cart_detail')


@login_required
@require_POST
def cart_remove(request, product_id):
    cart = get_object_or_404(Cart, user=request.user)
    product = get_object_or_404(Product, id=product_id)
    try:
        cart_item = cart.items.get(product=product)
    except CartItem.DoesNotExist:
        pass
    else:
        if cart_item.quantity - 1 <= 0:
            cart_item.delete()
        else:
            cart_item.quantity -= 1
            cart_item.save()

    return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% extends 'shop/base.html' %}

{% load static %}

{% block content %}
    <div class="container mt-5">
        <table class="table table-borderless table-hover">
            <thead class="bg-primary bg-gradient text-white">
            <tr>
                <th scope="col">Изображение</th>
                <th scope="col">Название</th>
                <th scope="col">Количество</th>
                <th scope="col">Цена за шт</th>
                <th scope="col">Общая цена</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart_items %}
                <tr class="bg-light">
                    <td>
                        {% csrf_token %}
                        <a href="{% url 'shop:product_detail' item.product.slug %}" target="_blank">
                            {% if item.product.image %}
                                <img src="{{ item.product.image.url }}" width="160" height="140" alt="Картинка">
                            {% else %}
                                <img src="{% static 'shop/img/no_image.png' %}" width="160" height="140" alt="Картинка">
                            {% endif %}
                        </a>
                    </td>
                    <td>{{ item.product.name }}</td>
                    <td>
                        <form>
                            {% csrf_token %}
                            <div class="btn-group btn-group-sm" role="group">
                                <button type="button" class="btn btn-outline-primary">{{ item.quantity }}</button>
                                <button type="button" class="btn btn-outline-primary"><i
                                        class="fas fa-plus" onclick="onAddToCart({{ item.product.id }})"></i>
                                </button>
                                <button type="button" class="btn btn-outline-primary"
                                        onclick="removeFromCart({{ item.product.id }})"><i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </form>
                    </td>
                    <td>{{ item.product.price }}</td>
                    <td>{{ item.total_price }}Р</td>
                </tr>
            {% endfor %}
            <tr class="bg-primary bg-gradient text-white">
                <th>Total</th>
                <th colspan="3"></th>
                <td>{{ total_price }}Р</td>
            </tr>
            </tbody>
        </table>
        <div class="text-end">
            <div class="btn-group" role="group">
                <a href="{% url 'shop:products_by_page' 1 %}" class="btn btn-outline-secondary">Продолжить</a>
                <a href="{% url 'orders:create_order' %}" class="btn btn-outline-primary">Создать заказ</a>
            </div>
        </div>
    </div>
{% endblock %}