app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.list_orders, name='list_orders'),
    path('create/', views.create_order, name='create_order'),
    path('<int:order_id>/pdf/', views.order_pdf, name='order_pdf'),
    path('delete/<int:o_id>/', views.delete_order, name='delete_order'),
]

orders/models.py
from django.contrib.auth.models import User
from django.db import models

from shop.models import Product


class Order(models.Model):
    NEW = 'NEW'
    PENDING = 'PENDING'
    PROCESSING = 'PROCESSING'
    SHIPPED = 'SHIPPED'
    DELIVERED = 'DELIVERED'
    CANCELED = 'CANCELED'
    STATUS_CHOICES = {
        NEW: 'Новый',
        PENDING: 'Ожидает оплаты',
        PROCESSING: 'В процессе оплаты',
        SHIPPED: 'Отправлен',
        DELIVERED: 'Доставлен',
        CANCELED: 'Отменён'
    }

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', related_name='orders')
    address = models.CharField(max_length=250, verbose_name='Адрес')
    postal_code = models.CharField(max_length=20, verbose_name='Почтовый индекс')
    city = models.CharField(max_length=100, verbose_name='Город')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')
    status = models.CharField(
        max_length=20,
        choices=tuple(STATUS_CHOICES.items()),
        default=NEW,
        verbose_name='Статус'
    )

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        related_name='items',
        on_delete=models.CASCADE,
        verbose_name='Заказ'
    )
    product = models.ForeignKey(
        Product,
        related_name='order_items',
        on_delete=models.CASCADE,
        verbose_name='Продукт'
    )
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    class Meta:
        verbose_name = 'Продукт в заказе'
        verbose_name_plural = 'Продукты в заказе'

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm, HiddenInput

from orders.models import Order


class OrderForm(ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all(), widget=HiddenInput())
    password = forms.CharField(widget=forms.PasswordInput, label='Подтвердите пароль')

    class Meta:
        model = Order
        fields = ['user', 'address', 'postal_code', 'city']

orders/views.py
from io import BytesIO

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template.loader import get_template
from xhtml2pdf import pisa

from cart.models import Cart
from orders.forms import OrderForm
from orders.models import Order, OrderItem
from shop.models import Product


@login_required
def create_order(request):
    cart = Cart.objects.get(user=request.user)
    if not cart.items.count() == 0:
        if request.method == 'POST':
            form = OrderForm(request.POST)
            if form.is_valid():
                with transaction.atomic():
                    order = form.save()
                    for item in cart.items.all():
                        product = Product.objects.get(id=item.product.id)
                        if product.amount - item.quantity >= 0:
                            product.amount -= item.quantity
                            quantity = item.quantity
                        else:
                            quantity = product.amount
                            product.amount = 0

                        OrderItem.objects.create(
                            order=order,
                            product=item.product,
                            quantity=quantity,
                            price=item.product.price
                        )
                        item.delete()
                        product.save()
                return redirect('orders:list_orders')
            else:
                messages.error(request, "Не удалось создать заказ, введите корректные данные")
                return redirect('orders:create')

        form = OrderForm(initial={'user': request.user})
        return render(request, 'orders/create.html', {'order_form': form})
    else:
        messages.error(request, 'Корзина пуста')
        return redirect('cart:cart_detail')


@login_required
def list_orders(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'orders/list.html', {'orders': orders})


@login_required
def delete_order(request, o_id):
    order = get_object_or_404(Order, id=o_id)
    if request.method == 'POST':
        order.delete()

    orders = Order.objects.filter(user=request.user)
    return render(request, 'orders/list.html', {'orders': orders})


def html_to_pdf(template_src, context_dict=None):
    if context_dict is None:
        context_dict = {}

    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None


@login_required
def order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    pdf = html_to_pdf("orders/pdf.html", {"order": order})
    return HttpResponse(pdf, content_type='application/pdf')

orders/templates/orders/create.html
{% extends 'shop/base.html' %}

{% load crispy_forms_filters %}


{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-6">
                <form method="post" class="w-75 m-auto" oninput="onConfirmPasswordOrder()">
                    {% csrf_token %}
                    {{ order_form|crispy }}
                    <button type="submit" class="btn btn-primary bg-gradient">Заказать</button>
                </form>
            </div>
            <div class="col-lg-6">
                <div class="card w-75 m-auto">
                    <div class="card-header text-start">Ваш заказ</div>
                    <div class="card-body">
                        <ul>
                            {% for item in cart.items.all %}
                                <div class="d-flex justify-content-between bd-highlight">
                                    <div>{{ item.quantity }}*{{ item.product.name }}</div>
                                    <div>{{ item.total_price }}Р</div>
                                </div>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="card-footer text-end">Всего: {{ total_price }}Р</div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/list.html
{% extends 'shop/base.html' %}

{% block content %}
    <div class="container mt-5">
        <table class="table table-borderless table-hover">
            <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Продукты</th>
                <th scope="col">Адрес</th>
                <th scope="col">Дата создания</th>
                <th scope="col">Стоимость</th>
                <th scope="col">Статус</th>
                <th scope="col">Выписка</th>
                <th scope="col">Действие</th>
            </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-sm btn-primary bg-gradient" type="button"
                                    id="dropdownProductsButton{{ forloop.counter }}"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                Список продуктов
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownProductsButton{{ forloop.counter }}">
                                {% for item in order.items.all %}
                                    <li><a class="dropdown-item" href="#">{{ item.quantity }}*{{ item.product.name }} -
                                        {{ item.get_cost }}Р</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </td>
                    <td>{{ order.address }}</td>
                    <td>{{ order.created_at }}</td>
                    <td>{{ order.get_total_cost }}Р</td>
                    <td>{{ order.get_status_display }}</td>
                    <td><a class="order-pdf" href="{% url 'orders:order_pdf' order.id %}">PDF</a></td>
                    <td>
                        <form method="post" action="{% url 'orders:delete_order' order.id %}">
                            {% csrf_token %}
                            <button type="submit"
                                    class="btn btn-danger btn-sm" {% if order.status != 'NEW' %} disabled{% endif %}>
                                Удалить
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

orders/templates/orders/pdf.html
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Заказ</title>
</head>
<style>
    table {
        width: 100%;
        border-spacing: 0;
        border-collapse: collapse;
        margin: 20px 0;
    }

    table th, table td {
        text-align: left;
        font-size: 14px;
        padding: 10px;
        margin: 0;
    }

    tbody tr:nth-child(odd) {
        background: #efefef;
    }

    thead th, tbody tr.total {
        background: #0d6efd;
        color: #fff;
        font-weight: bold;
    }

    .div-status {
        text-align: center;
    }

    .status {
        color: #3d86e7;
        text-transform: uppercase;
        font-weight: bold;
        font-size: 30px;
    }

</style>
<body>
<h1>Мир цветов</h1>
<p>
    Заказ №{{ order.id }}
    <br>
    <span class="secondary">
      {{ order.created_at|date:"M d, Y" }}
    </span>
</p>

<h3>От</h3>
<p>
    {{ order.user.first_name }} {{ order.user.last_name }}<br>
    {{ order.user.email }}<br>
    {{ order.address }}<br>
    {{ order.postal_code }}, {{ order.city }}
</p>

<h3>Продукты</h3>
<table>
    <thead>
    <tr>
        <th>Название</th>
        <th>Цена за шт</th>
        <th>Количество</th>
        <th>Общая стоимость</th>
    </tr>
    </thead>
    <tbody>
    {% for item in order.items.all %}
        <tr class="row{% cycle "1" "2" %}">
            <td>{{ item.product.name }}</td>
            <td class="num">{{ item.price }}Р</td>
            <td class="num">{{ item.quantity }}</td>
            <td class="num">{{ item.get_cost }}Р</td>
        </tr>
    {% endfor %}
    <tr class="total">
        <td colspan="3">Всего</td>
        <td class="num">${{ order.get_total_cost }}</td>
    </tr>
    </tbody>
</table>

<div class="div-status">
    <span class="status">{{ order.status }}</span>
</div>
</body>
</html>