app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.list_orders, name='list_orders'),
    path('create/', views.create_order, name='create_order'),
    path('<int:order_id>/pdf/', views.order_pdf, name='order_pdf'),
    path('delete/<int:o_id>/', views.delete_order, name='delete_order'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('where/', views.where, name='where'),
    path('<int:page>/', views.index, name='products_by_page'),
    path('products/<int:page>/<slug:category_slug>/', views.index, name='products_by_category'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('check_user/', views.check_user, name='check_user'),
    path('confirm_password/', views.confirm_password, name='confirm_password'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class ProductCategory(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=110, db_index=True, unique=True, verbose_name='Cтроковое представление в URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[1, self.slug])

    class Meta:
        verbose_name = 'Категория продукта'
        verbose_name_plural = 'Категории продуктов'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='products',
                                 verbose_name='Категория')
    name = models.CharField(max_length=30, verbose_name='Название продукта')
    slug = models.SlugField(max_length=35, unique=True, db_index=True, verbose_name='Cтроковое представление в URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание продукта')
    country = models.CharField(max_length=100, verbose_name='Страна поставщика')
    color = models.CharField(max_length=100, verbose_name='Цвет')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    amount = models.IntegerField(default=0, verbose_name='Количество')
    image = models.ImageField(upload_to='product_images/', blank=True, null=True, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.slug])

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

shop/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from shop.models import ProductCategory, Product


# Create your views here.


def index(request, page=1, category_slug=None):
    category = None
    message = None
    categories = ProductCategory.objects.all()
    sort = None
    direction = 'ASC'
    if 'sort' in request.GET:
        sort = request.GET['sort']
    if 'direction' in request.GET:
        direction = request.GET['direction']

    object_list = Product.objects.filter(amount__gt=0).all()
    if sort in ('name', 'price', 'country', 'created_at'):
        object_list = object_list.order_by(f"{'' if direction == 'ASC' else '-'}{sort}")
    if category_slug:
        category = get_object_or_404(ProductCategory, slug=category_slug)
        object_list = object_list.filter(category=category)

    if object_list.count() == 0:
        message = 'Нет доступных продуктов'

    paginator = Paginator(object_list, per_page=12)
    page_object = paginator.get_page(page)
    page_object.adjusted_elided_pages = paginator.get_elided_page_range(page)

    return render(
        request, 'shop/index.html',
        {
            'products': page_object,
            'categories': categories,
            'category': category,
            'message': message,
            'current_page': page,
            'sort': sort,
            'current_direction': direction,
            'next_direction': 'DESC' if direction == 'ASC' else 'ASC',
        }
    )


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, amount__gt=0)
    return render(request, 'shop/detail.html', {'product': product})


def where(request):
    return render(request, 'shop/where.html')

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мир цветов</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'shop/css/base.css' %}"/>
    {% block links %}{% endblock %}
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg px-5">
        <div class="container-fluid">
            <a class="navbar-brand px-1" href="{% url 'shop:index' %}">
                <img src="{% static 'shop/img/logo.png' %}" alt="logo" class="logo-image">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">О нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:index' %}">Каталог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:where' %}">Где нас найти?</a>
                    </li>
                </div>
                <div class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown-center">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'cart:cart_detail' %}">Корзина</a></li>
                                <li><a class="dropdown-item" href="{% url 'orders:list_orders' %}">Мои заказы</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Зарегистрироваться</a>
                        </li>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main>
    {% for message in messages %}
        <div class="alert alert-dismissible {{ message.tags }} w-75 m-auto" role="alert">
            <div>{{ message | safe }}</div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    <div id="alerts"></div>
    {% block content %}{% endblock %}
</main>
<footer>
    <div class="container border-top">
        <h5 class="my-3 text-center">© 2024 Мир цветов</h5>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.0.4/js.cookie.min.js"
        integrity="sha512-Nonc2AqL1+VEN+97F3n4YxucBOAL5BgqNwEVc2uUjdKOWAmzwj5ChdJQvN2KldAxkCxE4OenuJ/RL18bWxGGzA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'shop/js/functions.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

shop/templates/shop/detail.html
{% extends 'shop/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <div class="container p-4">
        <div class="row">
            <div class="col-lg-4">
                <img class="detail-product-image"
                     src="
                             {% if product.image %}{{ product.image.url }}{% else %}{% static 'shop/img/no_image.png' %}{% endif %}"
                     alt="Изображение">
            </div>
            <div class="col-lg-8 text-center d-flex flex-column justify-content-center">
                <h4>{{ product.name }}</h4>
                <h5>Категория: {{ product.category.name }}</h5>
                <p>Страна: {{ product.country }}, цвет: {{ product.color }}</p>
                <p class="text-muted">
                    {{ product.description }}
                </p>
                <h3>Цена: {{ product.price }}Р</h3>
                <small>Количество: {{ product.amount }}</small>
                {% if user.is_authenticated %}
                    <form class="mt-1">
                        {% csrf_token %}
                        <div class="d-flex justify-content-center" style="height: 38px">
                            <button type="button" onclick="onAddToCart({{ product.id }})"
                                    class="ms-1 btn btn-primary bg-gradient">
                                В корзину
                            </button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <div class="container my-2 m-auto text-center">
            <div class="btn-group m-auto" role="group" aria-label="Sorting Options">
                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        Категории
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item {% if category.slug == c.slug %}active{% endif %}"
                               href="{% url 'shop:products_by_page' 1 %}">Все</a></li>
                        {% for c in categories %}
                            <li><a class="dropdown-item {% if category.slug == c.slug %}active{% endif %}"
                                   href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>

                {# fas fa-sort-up - fas fa-sort - fas fa-sort-down #}
                <a href="{% if category %}{% url 'shop:products_by_category' current_page category.slug %}{% else %}{% url 'shop:products_by_page' current_page %}{% endif %}?sort=price&direction={{ next_direction }}"
                   class="btn btn-primary">
                    Цена <i class="fas {% if sort == 'price' %}{% if current_direction == 'ASC' %}fa-sort-down{% elif current_direction == 'DESC' %}fa-sort-up{% else %}fa-sort{% endif %}{% else %}fa-sort{% endif %}"></i>
                </a>
                <a href="{% if category %}{% url 'shop:products_by_category' current_page category.slug %}{% else %}{% url 'shop:products_by_page' current_page %}{% endif %}?sort=created_at&direction={{ next_direction }}"
                   class="btn btn-primary">
                    Новизна <i class="fas {% if sort == 'created_at' %}{% if current_direction == 'ASC' %}fa-sort-down{% elif current_direction == 'DESC' %}fa-sort-up{% else %}fa-sort{% endif %}{% else %}fa-sort{% endif %}"></i>
                </a>
                <a href="{% if category %}{% url 'shop:products_by_category' current_page category.slug %}{% else %}{% url 'shop:products_by_page' current_page %}{% endif %}?sort=country&direction={{ next_direction }}"
                   class="btn btn-primary">
                    Страна <i class="fas {% if sort == 'country' %}{% if current_direction == 'ASC' %}fa-sort-down{% elif current_direction == 'DESC' %}fa-sort-up{% else %}fa-sort{% endif %}{% else %}fa-sort{% endif %}"></i>
                </a>
                <a href="{% if category %}{% url 'shop:products_by_category' current_page category.slug %}{% else %}{% url 'shop:products_by_page' current_page %}{% endif %}?sort=name&direction={{ next_direction }}"
                   class="btn btn-primary">
                    Наименование <i class="fas {% if sort == 'name' %}{% if current_direction == 'ASC' %}fa-sort-down{% elif current_direction == 'DESC' %}fa-sort-up{% else %}fa-sort{% endif %}{% else %}fa-sort{% endif %}"></i>
                </a>
                <a href="{% url 'shop:products_by_page' current_page %}" class="btn btn-primary">Сбросить</a>
            </div>
        </div>
{#            <div class="col-md-6">#}
{#                <div class="card">#}
{#                <div class="card-header bg-primary bg-gradient text-white">Categories</div>#}
{#                <div class="card-body">#}
{#                    <ul class="nav nav-pills flex-column">#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link bg-gradient {% if not category %}active{% endif %}"#}
{#                               href="{% url 'shop:products_by_page' 1 %}">All</a>#}
{#                        </li>#}
{#                        {% for c in categories %}#}
{#                            <li class="nav-item">#}
{#                                <a class="nav-link bg-gradient {% if category.slug == c.slug %}active{% endif %}"#}
{#                                   href="{{ c.get_absolute_url }}">{{ c.name }}</a>#}
{#                            </li>#}
{#                        {% endfor %}#}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
        <div class="container py-4">
            {% if message %}
                <h3 class="text-center">{{ message }}</h3>
            {% else %}
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-3 my-2">
                            <div class="card product m-auto mt-1 h-100">
                                <img class="card-img-top"
                                        {% if product.image %}
                                     src="{{ product.image.url }}"
                                        {% else %}
                                     src="{% static 'shop/img/no_image.png' %}"
                                        {% endif %}
                                     alt="Product image">
                                <div class="card-body d-flex flex-column justify-content-center">
                                    <h4 class="card-title text-center">{{ product.name }}</h4>
                                    {#                                    <p class="card-text">{{ product.description|truncatewords:6 }}</p>#}
                                </div>
                                <div class="card-footer">
                                    <a href="{{ product.get_absolute_url }}" class="btn btn-primary bg-gradient w-100">
                                        Купить за {{ product.price }}Р
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="container mt-5">
                    <ul class="pagination justify-content-center">
                        {% if products.has_previous %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% if category %}{% url 'shop:products_by_category' 1 category.slug %}{% else %}{% url 'shop:products_by_page' 1 %}{% endif %}">First</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% if category %}{% url 'shop:products_by_category' products.previous_page_number category.slug %}{% else %}{% url 'shop:products_by_page' products.previous_page_number %}{% endif %}">Previous</a>
                            </li>
                        {% endif %}
                        {% for page_number in products.adjusted_elided_pages %}
                            {% if page_number == products.paginator.ELLIPSIS %}
                                <li class="page-item">
                                    <a class="page-link" href="">...</a>
                                </li>
                            {% else %}
                                <li class="page-item {% if page_number == products.number %}active{% endif %}">
                                    <a class="page-link"
                                       href="{% if category %}{% url 'shop:products_by_category' page_number category.slug %}{% else %}{% url 'shop:products_by_page' page_number %}{% endif %}">{{ page_number }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if products.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% if category %}{% url 'shop:products_by_category' products.next_page_number category.slug %}{% else %}{% url 'shop:products_by_page' products.next_page_number %}{% endif %}">Next</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% if category %}{% url 'shop:products_by_category' products.paginator.num_pages category.slug %}{% else %}{% url 'shop:products_by_page' products.paginator.num_pages %}{% endif %}">Last</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

shop/templates/shop/where.html
{% extends 'shop/base.html' %}

{% load static %}

{% block content %}
    <div class="container mt-5 px-5">
        <div class="row">
            <div class="col-sm mt-1">
                <div class="m-auto h-100 p-4 d-flex flex-column justify-content-center">
                    <h4 class="text-center mb-3">Контакты</h4>
                    <p class="text-center mb-3">Номер телефона: +77777777777</p>
                    <p class="text-center mb-3">Почта: flowers@mail.ru</p>
                </div>
            </div>
            <div class="col-sm text-center mt-1">
                <a href="https://yandex.ru/maps/?um=constructor%3Ac671917f693283a52fbf6708a535ba654b8deffc7ed51279a7675927fbcc271b&amp;source=constructorStatic"
                   target="_blank"><img
                        src="https://api-maps.yandex.ru/services/constructor/1.0/static/?um=constructor%3Ac671917f693283a52fbf6708a535ba654b8deffc7ed51279a7675927fbcc271b&amp;width=450&amp;height=450&amp;lang=ru_RU"
                        alt="" style="border-radius: 50%;"/></a>
            </div>
        </div>
    </div>
{% endblock content %}